### ISSUE TITLE
Overviews creation fails with ERROR:  function min(boolean) does not exist

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#211]
Relevant traces from log:
```
2016-03-16 17:52:56 UTC: Proceeding to register
2016-03-16 17:52:56 UTC: Before renaming from importer_85e4e0cceb9c11e5af550ef24382571b to my_anonymized_table
2016-03-16 17:52:56 UTC: Before moving schema 'my_anonymized_table' from cdb_importer to rtorre
2016-03-16 17:52:56 UTC: Before persisting metadata 'my_anonymized_table' data_import_id: e8eaf693-896f-4901-9109-6e0ec40008b0
2016-03-16 18:06:58 UTC: Table 'my_anonymized_table' registered
2016-03-16 18:06:58 UTC: Will create overviews for rtorre.my_anonymized_table
2016-03-16 18:07:43 UTC: Exception: PG::Error: ERROR:  function min(boolean) does not exist
LINE 5: ...::integer AS ratecodeid,CASE count(*) WHEN 1 THEN MIN(store_...
                                                             ^
HINT:  No function matches the given name and argum
```

Ruby trace:
```
app/services/carto/overviews_service.rb:11:in `create_overviews'
services/importer/lib/importer/overviews.rb:52:in `block (2 levels) in create_overviews!'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/overviews.rb:51:in `block in create_overviews!'
app/models/user.rb:569:in `block (2 levels) in transaction_with_timeout'
app/models/user.rb:566:in `block in transaction_with_timeout'
app/models/user.rb:548:in `in_database'
app/models/user.rb:565:in `transaction_with_timeout'
services/importer/lib/importer/overviews.rb:49:in `create_overviews!'
services/importer/lib/importer/overviews.rb:75:in `create_overviews!'
app/connectors/importer.rb:97:in `create_overviews'
app/connectors/importer.rb:57:in `block in run'
app/connectors/importer.rb:56:in `each'
app/connectors/importer.rb:56:in `run'
app/models/data_import.rb:667:in `new_importer'
app/models/data_import.rb:393:in `dispatch'
app/models/data_import.rb:174:in `run_import!'
```

**Comment by rafatower** [comment]
There's a `boolean` column indeed in that table. Once removed, it worked like a charm. Here's the offending line

 https://github.com/CartoDB/cartodb-postgresql/blob/2dc6ec618fd35e75173e8a24a190607e9544d44c/scripts-available/CDB_Overviews.sql#L490

should be easy to reproduce and fix.
